:PROPERTIES:
:ID:       86dd0d8d-fd13-42e1-9214-de014bfc3ed8
:END:
#+title: Water Cycle

Also called the *hydrologic cycle*, the water cycle describes how water is distributed around the environment.

The water cycle is easier to remember than other cycles since most of the processes are the result of the
physical phase changes of water as a gas, a liquid, and a solid.

The water cycle is powered by the Sun, as it heats and _evaporates_ the water as water vapor. Plants and
animals also release water vapor through _transpiration_ and _respiration_, respectively.

As it goes high up the atmosphere (near the trophosphere and stratosphere), water condenses into small water
droplets which form clouds. These water droplets may mix with other aerosols or freeze because of dropping
temperatures. This results to various forms of *precipitation* such as sleet, rain, and snow.

Once water lands onto the ground, it will flow through the surface or even _percolates_ into the lithosphere
as /*runoffs*/. These process forms lakes, rivers and groundwater and may flow into the ocean.

The water cycle is very important to consider when it comes to climate and weather. Water vapor itself is
greenhouse gas, and can be a defining factor if you will have a rainy day or a very hot day.

Water is important because most organisms require water to survive and thrive. We humans are 70% water. Plants
require water for photosynthesis. Animals require water for breaking down sugar during respiration.
