:PROPERTIES:
:ID:       2fdf710c-3e4c-486b-8e0c-c6b060e76496
:END:
#+title: Nitrogen Cycle

This cycle describes the movement of nitrogen between the atmosphere, biosphere, hydrosphere and
the geosphere. _Gaseous nitrogen (N_{2}) is useless on its own_. Fortunately, natural processes
such as lightning strikes */fixes/* nitrogen to usable forms such as _nitrates_, and _nitrites_. Other
organisms, such as legumes, have species of bacteria and fungi on their root nodes that /*fixes*/
nitrogen into usable form. This process is called _*nitrogen-fixation*_.

Much like the carbon cycle, nitrogen also undergoes similar processes as well such as [[id:c7b3e9b1-68b8-4a16-8c58-c09b44256111][Sequestration]], [[id:30d5d68e-bc64-41d3-bfc0-7d77270d8acf][Decomposition]], and [[id:035a930f-bce6-47a7-8005-6b58bc071ba1][Dissolution]].

These are some processes that are maybe unique to nitrogen.

* Denitrification
:PROPERTIES:
:ID:       79b638f0-d2f8-4c8d-851e-2fe8de3fe0c0
:END:

This is the opposite process of [[id:8b1984ad-cec5-4b65-9f57-60627b10789b][Nitrification]] where nitrates and nitrites are turned back to gaseous
nitrogen or nitrous oxide.

* Nitrification
:PROPERTIES:
:ID:       8b1984ad-cec5-4b65-9f57-60627b10789b
:END:

This is what we refer as _nitrogen-fixation_. This refers to the process where nitrogen is converted
into soluble nitrites (NO_{2}) and nitrates (NO_{3}).

Lightning nitrogen-fixation requires lightning to "fix" nitrogen into nitrites and nitrates.

Microbial nitrogen-fixation converts ammonia and ammonium into nitrites and nitrates.

* Mineralization
:PROPERTIES:
:ID:       06940715-d767-4db6-9b25-f700c1e838df
:END:

This is the process of converting organic substances as inorganic forms that can be used for plants
and other microorganisms.
