:PROPERTIES:
:ID:       adda8b0d-b40c-47e5-9027-a4ad3840eb2a
:END:
#+author: Soc Virnyl Estela
#+email: socvirnyl.estela@gmail.com
#+date: 2023-07-26
#+title:rypper

* Rationale

Rypper is my first serious [[id:ac5483d3-ad5a-4256-a4a5-9c8a2bdf86a3][Rust]] project or even programming project in a very long while.

I will log a journal every time I have done something related to the project as =org-note=.

* TODO Implement the following features per crate [%]
DEADLINE: <2024-01-01 Mon>

:LOGBOOK:
- Note taken on [2023-06-27 Tue 22:25] \\
  So far so good. I am liking the Emacs Org Mode features especially
  =org-agenda=. Glad that it all worked out for this project journal
  for *Rypper*.
:END:

- [ ] Use [[https://github.com/rust-lang/hashbrown][hasbrown]]. Disallow type for std hashmap and hashset at =clippy.toml=
- [X] Add rustfmt using nightly features.

** TODO =rypper-utils [0%]
SCHEDULED: <2023-08-31 Thu>

- [ ] Implement simple web requests to repositories [0%]
  - [ ] Investigate mirror behavior further [0%]
    - [ ] Mirror D-O-O
    - [ ] Mirror Redirectors
    - [ ] List of HEADERs to use
  - [ ] Fetching files [0%]
    - [ ] Remote files
    - [ ] Local files
- [ ] Verify file signatures [0%]
  - [ ] Add option to not verify signatures? Should be at rypper-core?
    
** TODO =rypper-reader= [0%]
SCHEDULED: <2023-07-15 Sat>
:PROPERTIES:
:ID:       1f30bfbf-98ed-4d39-b6d5-9e338dade38f
:END:
:LOGBOOK:
- Note taken on [2023-07-31 Mon 15:53] \\
  tests for repoconfig files are more towards about some corner cases
- Rescheduled from "[2023-07-04 Tue]" on [2023-07-03 Mon 23:50]
- Rescheduled from "[2023-07-01 Sat]" on [2023-07-03 Mon 23:48]
- Note taken on [2023-06-27 Tue 22:29] \\
  During my query from the people for =RepoConfig= struct,
  I decided to go for =impl Default for RepoConfig= to implement
  the =default= method for that struct. I was thinking of using
  the Builder approach but it's a bit overkill for a small project
  that is yet to become bigger.
  
  William Brown, also known as [[https://github.com/firstyear][firstyear]], taught me a little bit about
  [[https://wireshark.org][wireshark]] to check how =zypper= and mirrors work for openSUSE/SUSE.
  What I learned was that =zypper= is very inefficient when it checks for
  files in the mirrors. Not to mention, the fact that multiple mirrors exist
  loses the potential of asynchronous or what most people call "parallel"
  downloads. firstyear told me that we don't really need "parallel downloads.
  We just actually need to avoid having that inefficient query from zypper
  when it downloads a file from a mirror.
  
  I also decided to probably check if I have the energy to do a side project,
  a [de](serializer) for ini format files. I can probably just fork the existing
  project and improve upon it but I also wished I can start from scratch
  so I can really learn the =serde= crate.
  
  Anyway, that's it for this log for now 🫡
:END:
- [ ] Read =*.repo= config files e.g. from =/etc/zypp/repos.d/=. [0%]
  - [ ] Migrate to another ini crate [[https://github.com/QEDK/configparser-rs][configparser]].
  - [ ] Remove ini_core. LOL
- [ ] Read =*.xml= metadata files fetched from mirrors e.g. =repomd.xml=, =*.meta4=. [0%]
  - [ ] Repo files
  - [ ] Repomd files (XML)
  - [ ] Metalink and Meta4 (XML)
- [-] Add unit tests [50%]
  - [X] reading repo files
  - [ ] reading xml files

** TODO =rypper-cli= [50%]
:PROPERTIES:
:ID:       21986092-61ae-4299-b2bc-0bda84a4317e
:END:

- [X] Should I use clap? YES
- [ ] Integrate commands. Probably from reader and util.

** TODO  =rypper-tui= [0%]
SCHEDULED: <2023-09-01 Fri>
:PROPERTIES:
:ID:       666b58da-0200-41f3-b070-66641c3ac37f
:END:

- [ ] Create UI/UX sample, either as a UML, or Tide, or a sketch.
- [ ] Implement layout logic.
- [ ] Ask for feedback. Rinse and Repeat

** TODO =rypper-core= [0%]
:PROPERTIES:
:ID:       06c04349-2441-4fa5-bf00-536a7d0197d4
:END:

- [ ] Grab all other stuff from other rypper libraries
- [ ] Set this crate as default "gobbler" binary (grabs other rypper stuff, hence, core).

* Progress notes

- [[id:1f104a66-4136-4e3d-b043-7a9d414b305d][Progress with reqwest and HTTP request to openSUSE repos]] at [[id:6890316d-3e57-4bf0-9e26-75934718d4d0][2023-07-26]]
- [[id:3a7b177c-eeb6-49ee-a3e4-719da20450c0][2023-07-29]] contains zypper's default behavior and the defaults for repoconfigs.

** TODO RepoConfig struct should use Option
SCHEDULED: <2023-07-29 Sat>

** DONE Write own ini parser?
CLOSED: [2023-08-01 Tue 22:18]
:LOGBOOK:
- Note taken on [2023-08-01 Tue 22:18] \\
  We didn't write one LOL
:END:
Currently, the ini-parser crate has a ton of features I don't need. openSUSE repo configs
in ini are too simple. It has the following: Alias and Parameters. We only need to parse
the Alias e.g. =[X11_Wayland]=, and the parameters e.g. =name=, =url=, =path= etc.

As an example, a config pointing to the network project repo data may look like this.

#+begin_src ini
[network]
name=Networking services and related tools (openSUSE_Tumbleweed)
enabled=1
autorefresh=0
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/network/openSUSE_Tumbleweed/repodata/repomd.xml.key
baseurl=https://mirrorcache-jp.opensuse.org/repositories/network/openSUSE_Tumbleweed/
#+end_src

